# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '设计模式' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 设计模式
  pod 'SDWebImage', '~> 5.0.3'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'Masonry', '~> 1.1.0'
end
